#!/usr/bin/env bash

# SPDX-License-Identifier: BSD-3-Clause
# Copyright 2026 <Nitrux Latinoamericana S.C. <hello@nxos.org>>


# -- Build kernel Debian packages.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC_NAME="$(cat "$ROOT_DIR/work/source-dir")"
SRC_DIR="$ROOT_DIR/work/$SRC_NAME"

cd "$SRC_DIR"

make CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1 -j"$KERNEL_MAKE_JOBS" bindeb-pkg LOCALVERSION="$KERNEL_LOCALVERSION" KDEB_PKGVERSION="$(make kernelversion)-${KERNEL_PKG_RELEASE}"
